addons:
  apt:
    packages:
      - pandoc
      - libpcre3
install:
  - pip install cython numpy pytest
script:
  - make test
  - .travis/install_swig.sh
  - export PATH=$(/bin/pwd)/extern_pkgs/swig/bin:$PATH
  - cd benchmarks
  - make
matrix:
  include:
    - language: python
      python: 2.7
    - language: python
      python: 3.4
    - language: python
      python: 3.5
    - language: python
      python: 3.6
    - os: linux
      language: r
      before_install:
        - cd lang/r
        - make setup
        - cd build/camog
      install:
        - Rscript -e 'install.packages("devtools"); devtools::install_deps(dependencies = TRUE)'
      script:
        - R CMD build .
        - R CMD check *tar.gz
    - os: osx
      # Travis doesn't support Python on OSX, so use generic
      language: generic
      before_install:
        - uname -a
        - brew update
        - brew install python2 || true
        - virtualenv venv -p python2
        - . venv/bin/activate
      install:
        - pip install numpy pytest
      script:
        - make test
