language: python
matrix:
    include:
        - os: linux
          python: 2.7
        # Travis doesn't support Python on OSX, so use generic
        - os: osx
          language: generic
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install python2; virtualenv venv -p python2; . venv/bin/activate; fi
  - uname -a
install:
  - pip install numpy pytest
script:
  - make test
