addons:
  apt:
    packages:
      - pandoc
      - libpcre3
install:
  - pip install cython numpy pytest
script:
  - make test
deploy:
  provider: pypi
  user: walshb
  password:
    secure: Ejhvmkp3P1I3Xp2pZAS3tholZCdlIm81GTQP/4mctqkZibm8HiNvJenBCZ8M+dPoIQk0OmKByWwKfEMob8MFnY3x0sUfqzKBiFEi31LdAYGnEGXCE1XqgKX0An9hmOHDky01rddPdI7pxlbbTFDcGO9LOurrf8lrS+mq2+ks7ROhCjQTOMs1oElKTo8Bri3/bN4W4esoOt5TgWMa5yu/5BuRXSxSYJzq8svjEQ6HzdSbqAu1kYEn1hAJRImnkT8jZZ2jZsqxGDqMWxI95DLNXj9aNwrKpMeHtJ4a5vThEMl9GxcM8hON2p1xWsEjVetjS+h3fo79gEdXUpPQ/pLtHL3En6/WLosRWQHtdw/kpftXUgbfWkQMDigChbKMshzkZtzL6MdQHolK4jGpZD0jkjWxm20yVX9HuLGtinV84eErq6Ytx9x8BMvGiZ4jr1x6r4/pgQUmemZzDVu5AIQkLsr22eBJkOlQv0ZASNsNWEdCWEz8D2D6iMeVnbxTGa+U/aeH4LkPnsnHjcYWwk6JK1v2Th0RLUAZUW+kZK0r03wVxjtqpeL6nJDOrPeeblgwzaLsh1Qrj8j1yuRzN3WfdX5+2SiV8mFs1DxGm4jue7mFPexXrf+UECSO8XDKcEDh4OrDvdC2pby6ZtNMfMnuLwhl7Ag1KXPVw7iKdZ7useo=
  distributions: "sdist bdist_egg"
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - .travis/install_swig.sh
  - export PATH=$(/bin/pwd)/extern_pkgs/swig/bin:$PATH
  - cd benchmarks
  - make
matrix:
  include:
    - language: python
      python: 2.7
    - language: python
      python: 3.4
    - language: python
      python: 3.5
    - language: python
      python: 3.6
    - os: linux
      language: r
      before_install:
        - cd lang/r
        - make setup
        - cd build/camog
      install:
        - Rscript -e 'install.packages("devtools"); devtools::install_deps(dependencies = TRUE)'
      script:
        - R CMD build .
        - R CMD check *tar.gz
      deploy:
        provider: script
        script: /bin/true
      after_deploy:
        - /bin/true
    - os: osx
      # Travis doesn't support Python on OSX, so use generic
      language: generic
      before_install:
        - uname -a
        - brew update
        - brew install python2 || true
        - curl -LO https://pypi.python.org/packages/source/v/virtualenv/virtualenv-16.0.0.tar.gz
        - tar -xf virtualenv-16.0.0.tar.gz
        - python2 virtualenv-16.0.0/virtualenv.py -p python2 myenv
        - . myenv/bin/activate
      install:
        - pip install numpy pytest
      script:
        - make test
      after_deploy:
        - /usr/bin/true
