matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      install:
        - pip install numpy pytest
      script:
        - make test
    - os: linux
      language: r
      before_install:
        - cd lang/r
        - make setup
        - cd build/camog
    - os: osx
      # Travis doesn't support Python on OSX, so use generic
      language: generic
      before_install:
        - uname -a
        - brew update
        - brew install python2 || true
        - virtualenv venv -p python2
        - . venv/bin/activate
      install:
        - pip install numpy pytest
      script:
        - make test
